service: blog-image-resize-ondemand # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1


custom:
  envName: '${self:provider.stage}'
  apigwBinary:
    types:
      - '*/*'

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
        path: resize-image
        method: get
        contentHandling: CONVERT_TO_BINARY
      - http: 'ANY {proxy+}'
        path: resize-image
        method: get
        contentHandling: CONVERT_TO_BINARY

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-apigwy-binary